#+ summary: "Retrieve the average NitrogenTotal value for a specific geospatial region"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ enumerate:
#+   - physioChemicalProperty:
#+     - http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExchangeableBases	
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumTotalElements	
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurExtractableElements	
#+     - http://w3id.org/glosis/model/layerhorizon#AcidityExchangeable	
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumTotalElements	
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExchangeableBases	
#+     - http://w3id.org/glosis/model/layerhorizon#SandFractionTexture	
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExtractableElements	
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExtractableElements	
#+     - http://w3id.org/glosis/model/layerhorizon#BoronExtractableElements	
#+     - http://w3id.org/glosis/model/layerhorizon#CopperExtractableElements	
#+     - http://w3id.org/glosis/model/layerhorizon#IronTotalElements	
#+     - http://w3id.org/glosis/model/layerhorizon#ElectricalConductivity	
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumTotalElements	
#+     - http://w3id.org/glosis/model/layerhorizon#ClayFractionTexture	
#+     - http://w3id.org/glosis/model/layerhorizon#HydraulicConductivity	
#+     - http://w3id.org/glosis/model/layerhorizon#SiltFractionTexture	
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonTotal	
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonInorganic	
#+     - http://w3id.org/glosis/model/layerhorizon#ZincTotalElements	
#+     - http://w3id.org/glosis/model/layerhorizon#OrganicMatter	
#+     - http://w3id.org/glosis/model/layerhorizon#PH	
#+ defaults:
#+   - physioChemicalProperty: http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+ transform: {
#+   "avg_nitrogen_total": "?avg_nitrogen_total",
#+   "$anchor": "avg_nitrogen_total",
#+ }


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX iso: <http://w3id.org/glosis/model/iso28258/2013#>

SELECT (AVG(?value) as ?avg_nitrogen_total)
WHERE {
    ?obs a ?_physioChemicalProperty_iri ;
         sosa:hasResult ?res ;
         sosa:hasFeatureOfInterest ?lay .
    ?res qudt:numericValue ?value .
    ?site iso:Site.typicalProfile/iso:Profile.element ?lay ;
         geo:hasGeometry/geo:asWKT ?geom .
    OPTIONAL { ?s ?p ?_geoWKT }
    FILTER (geof:sfIntersects(?geom, bif:st_geomfromtext(?_geoWKT)))
}
