#+ summary: "Retrieve the average NitrogenTotal value for a specific geospatial region"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ enumerate:
#+   - physioChemicalProperty:
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AcidityExchangeable
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SandFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#BoronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#IronTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ElectricalConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ClayFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#HydraulicConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#SiltFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonTotal
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonInorganic
#+     - http://w3id.org/glosis/model/layerhorizon#ZincTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#OrganicMatter
#+     - http://w3id.org/glosis/model/layerhorizon#PH
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonOrganic
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusRetention
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ZincExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#SolubleSalts
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#EffectiveCec
#+     - http://w3id.org/glosis/model/layerhorizon#HydrogenExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#BaseSaturation
#+     - http://w3id.org/glosis/model/layerhorizon#Gypsum
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#TotalCarbonateEquivalent
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityFineEarth
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityWholeSoil
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+     - http://w3id.org/glosis/model/layerhorizon#IronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CoarseFragments
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#CationExchangeCapacitycSoil
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AvailableWaterHoldingCapacity
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#Porosity
#+     - http://w3id.org/glosis/model/layerhorizon#BoronTotalElements
#+ defaults:
#+   - physioChemicalProperty: http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+ transform: {
#+   "avg_physioChemicalPropertytotal": "?avg_physioChemicalPropertytotal",
#+   "$anchor": "avg_physioChemicalPropertytotal",
#+ }


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX iso: <http://w3id.org/glosis/model/iso28258/2013#>

SELECT (AVG(?value) as ?avg_physioChemicalPropertytotal)
WHERE {
    ?obs a ?_physioChemicalProperty_iri ;
         sosa:hasResult ?res ;
         sosa:hasFeatureOfInterest ?lay .
    ?res qudt:numericValue ?value .
    ?site iso:Site.typicalProfile/iso:Profile.element ?lay ;
         geo:hasGeometry/geo:asWKT ?geom .
    OPTIONAL { ?s ?p ?_geoWKT }
    FILTER (geof:sfIntersects(?geom, bif:st_geomfromtext(?_geoWKT)))
}
