#+ summary: "Retrieve the average NitrogenTotal value for a specific geospatial region"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ enumerate:
#+   - usedProcedure:
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph0-nh4cl
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-m3
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph8-unkn
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph0-cohex
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac-aas
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-edta
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac-fp
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph8-bacl2tea
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-m3-spec
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-unkn
#+     - http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_cacl2
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap15
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-kurtz-bray
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nh4-co3-2-ambic1
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m3-spec
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m1
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-h2so4-nelson
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_dtpa
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap14
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-bray1
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_edta
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m2
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_naoac-morgan
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_capo4
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hotwater
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nahco3-olsen-dabin
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nh4ch3ch-oh-cooh-leuven
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_c6h8o7-reeuwijk
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-bray2
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m3
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap21
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hno3
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nahco3-olsen
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap20
#+     - http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_h2so4-truog
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-kcl1m
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph7-caoac
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph8-unkn
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-unkn
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph8-bacl2tea
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph7-unkn
#+     - http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-nh4cl
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-beaker
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-adj100
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-fld
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-beaker
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-fld
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp-beaker
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp-pipette
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-adj100
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-adj100
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-fld
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-disp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp-laser
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-disp-spec
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-50-2000u-nodisp-hydrometer-bouy
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-20-2000u-nodisp-hydrometer
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-nodisp
#+     - http://w3id.org/glosis/model/procedure#textureProcedure-SaSiCl_2-64-2000u-disp
#+     - http://w3id.org/glosis/model/procedure#coarseFragmentsProcedure-CrsFrg_fld
#+     - http://w3id.org/glosis/model/procedure#coarseFragmentsProcedure-CrsFrg_lab
#+     - http://w3id.org/glosis/model/procedure#coarseFragmentsProcedure-CrsFrg_fldcls
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-Ksat_dblring
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-Ksat_invbhole
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-KSat_calcul-ptf-saxton
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-Ksat_bhole
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-KSat_calcul-ptf
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-KSat_calcul-ptf-genuchten
#+     - http://w3id.org/glosis/model/procedure#hydraulicConductivityProcedure-Ksat_column
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-nelson
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-mt
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-kurmies
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-tiurin
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-jackson
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-lt
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-ht-analyser
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-spec
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-ht
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-spec
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-walkleyblack
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-knopp
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-kalembra
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-ht-analyser
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-ht
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-lt
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-mt
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_acid-dc-lt-loi
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_wc-cro3-nrcs6a1c
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_calcul-tc-ic
#+     - http://w3id.org/glosis/model/procedure#carbonOrganicProcedure-OrgC_dc-lt-loi
#+     - http://w3id.org/glosis/model/procedure#phosphorusRetentionProcedure-RetentP_unkn-spec
#+     - http://w3id.org/glosis/model/procedure#phosphorusRetentionProcedure-RetentP_blakemore
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-unkn
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-baoac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-bacl2tea
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-licl2tea
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph7-nh4oac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-kcl
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-nh4cl
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph-unkn-lioac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph7-edta
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph-unkn-cacl2
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-bacl2
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-naoac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-cohex
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-unkn
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph7-unkn
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph-unkn-m3
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph8-nh4oac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-nh4oac
#+     - http://w3id.org/glosis/model/procedure#cationExchangeCapacitySoilProcedure-CEC_ph0-ag-thioura
#+     - http://w3id.org/glosis/model/procedure#textureSumProcedure-SumTxtr_calcul
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-2.5
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-10
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-5
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-1
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-ECe_sat
#+     - http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-2
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy04
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy01
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy05
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy06
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy02
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy07
#+     - http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy03
#+     - http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc100wp
#+     - http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc200wp
#+     - http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc300wp
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn08
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn04
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-spec
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_kjeldahl
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-ht-leco
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_calcul-oc10
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_bremner
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_calcul
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_h2so4
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn06
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_nelson
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_kjeldahl-nh4
#+     - http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-ht-dumas
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-10
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-2.5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_sat
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-2
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-2
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-10
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_sat
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-1
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_sat
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-2.5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-2
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-2.5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-1
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_sat
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_unkn-spec
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-10
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-1
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-10
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-1
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-2.5
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-2
#+     - http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O
#+     - http://w3id.org/glosis/model/procedure#carbonInorganicProcedure-InOrgC_calcul-caco3
#+     - http://w3id.org/glosis/model/procedure#carbonInorganicProcedure-InOrgC_calcul-tc-oc
#+     - http://w3id.org/glosis/model/procedure#porosityProcedure-Poros_calcul-pf0
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca01
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-dc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca05
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-hcl-dc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-ch3cooh-dc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca10
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca02
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-hcl-unkn
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca06
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-nodc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-ch3cooh-unkn
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h2so4-nodc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_calcul-tc-oc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h3po4-unkn
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca11
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca12
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h2so4-unkn
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca03
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca07
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h3po4-dc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-ch3cooh-nodc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca04
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca08
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-hcl-nodc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h3po4-nodc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_ca09
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-h2so4-dc
#+     - http://w3id.org/glosis/model/procedure#totalCarbonateEquivalentProcedure-CaCO3_acid-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-cl-od
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-co-fc
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-cl-fc
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-co-od
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-co-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-rpl-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityWholeSoilProcedure-BlkDensW_we-cl-unkn
#+     - http://w3id.org/glosis/model/procedure#baseSaturationProcedure-BSat_calcul-cec
#+     - http://w3id.org/glosis/model/procedure#baseSaturationProcedure-BSat_calcul-ecec
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_hcl-aquaregia
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp04
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp09
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_xrd
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp10
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp05
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp06
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_unkn
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_hcl
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_h2so4
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_xrf
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_xrf-p
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_nh4-6mo7o24
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp07
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_xtf-t
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp03
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_hno3-aquafortis
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_tp08
#+     - http://w3id.org/glosis/model/procedure#totalElementsProcedure-Total_hclo4
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-unkn-fc
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-cl-od
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-cl-fc
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-co-od
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-unkn-od
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-co-fc
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-rpl-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-cl-unkn
#+     - http://w3id.org/glosis/model/procedure#bulkDensityFineEarthProcedure-BlkDensF_fe-co-unkn
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_ud-cl
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_d
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_d-cl
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_calcul-ptf
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_d-ww
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_d-cl-ww
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_ud-co
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_ud
#+     - http://w3id.org/glosis/model/procedure#moistureContentProcedure-VMC_calcul-ptf-brookscorey
#+     - http://w3id.org/glosis/model/procedure#organicMatterProcedure-TotHumC_unkn
#+     - http://w3id.org/glosis/model/procedure#organicMatterProcedure-FulAcidC_unkn
#+     - http://w3id.org/glosis/model/procedure#organicMatterProcedure-OrgM_calcul-oc1.73
#+     - http://w3id.org/glosis/model/procedure#organicMatterProcedure-HumAcidC_unkn
#+     - http://w3id.org/glosis/model/procedure#effectiveCecProcedure-EffCEC_calcul-ba
#+     - http://w3id.org/glosis/model/procedure#effectiveCecProcedure-EffCEC_calcul-b
#+     - http://w3id.org/glosis/model/procedure#carbonTotalProcedure-TotC_calcul-ic-oc
#+     - http://w3id.org/glosis/model/procedure#carbonTotalProcedure-TotC_dc-mt
#+     - http://w3id.org/glosis/model/procedure#carbonTotalProcedure-TotC_dc-ht-spec
#+     - http://w3id.org/glosis/model/procedure#carbonTotalProcedure-TotC_dc-ht
#+     - http://w3id.org/glosis/model/procedure#carbonTotalProcedure-TotC_dc-ht-analyser
#+     - http://w3id.org/glosis/model/procedure#solubleSaltsProcedure-SlbAn_calcul-unkn
#+     - http://w3id.org/glosis/model/procedure#solubleSaltsProcedure-SlbCat_calcul-unkn
#+   - physioChemicalProperty:
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AcidityExchangeable
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SandFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#BoronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#IronTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ElectricalConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ClayFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#HydraulicConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#SiltFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonTotal
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonInorganic
#+     - http://w3id.org/glosis/model/layerhorizon#ZincTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#OrganicMatter
#+     - http://w3id.org/glosis/model/layerhorizon#PH
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonOrganic
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusRetention
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ZincExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#SolubleSalts
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#EffectiveCec
#+     - http://w3id.org/glosis/model/layerhorizon#HydrogenExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#BaseSaturation
#+     - http://w3id.org/glosis/model/layerhorizon#Gypsum
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#TotalCarbonateEquivalent
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityFineEarth
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityWholeSoil
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+     - http://w3id.org/glosis/model/layerhorizon#IronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CoarseFragments
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#CationExchangeCapacitycSoil
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AvailableWaterHoldingCapacity
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#Porosity
#+     - http://w3id.org/glosis/model/layerhorizon#BoronTotalElements
#+ defaults:
#+   - physioChemicalProperty: http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+   - usedProcedure: http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O
#+ transform: {
#+   "avg_physioChemicalPropertytotal": "?avg_physioChemicalPropertytotal",
#+   "$anchor": "avg_physioChemicalPropertytotal",
#+ }


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX iso: <http://w3id.org/glosis/model/iso28258/2013#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ramon: <http://rdfdata.eionet.europa.eu/ramon/ontology/>

SELECT (AVG(?value) as ?avg_physioChemicalPropertytotal)
WHERE {
    ?obs a ?_physioChemicalProperty_iri ;
         sosa:hasResult ?res ;
         sosa:hasFeatureOfInterest ?lay ;
         sosa:usedProcedure ?_usedProcedure_iri .
    ?res qudt:numericValue ?value .
    ?site iso:Site.typicalProfile/iso:Profile.element ?lay ;
         geo:hasGeometry/geo:asWKT ?geom .
    {
      SELECT ?g_nuts
      WHERE {
        ?n a ramon:NUTSRegion .
        ?n rdfs:label ?l .
        ?n geo:asWKT ?g_nuts .
        ?l bif:contains ?_nutsCode .
      } limit 1
    }
    FILTER (geof:sfIntersects(?geom, ?g_nuts))
}
