#+ summary: "Retrieve the observations, for a specific physioChemical property that have value over a specified threshold (e.g., 2) from multiple data sources (foodie and isric)"
#+ description: "NOTE: make sure response content type is application/json"
#+ endpoint: "https://www.foodie-cloud.org/sparql"
#+ tags: [ "json" ]
#+ method: "GET"
#+ pagination: 100
#+ enumerate:
#+   - physioChemicalProperty:
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AcidityExchangeable
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SandFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#BoronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#IronTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ElectricalConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#ClayFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#HydraulicConductivity
#+     - http://w3id.org/glosis/model/layerhorizon#SiltFractionTexture
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonTotal
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonInorganic
#+     - http://w3id.org/glosis/model/layerhorizon#ZincTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#OrganicMatter
#+     - http://w3id.org/glosis/model/layerhorizon#PH
#+     - http://w3id.org/glosis/model/layerhorizon#CarbonOrganic
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusRetention
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#ZincExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#SolubleSalts
#+     - http://w3id.org/glosis/model/layerhorizon#CadmiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#MolybdenumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#EffectiveCec
#+     - http://w3id.org/glosis/model/layerhorizon#HydrogenExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#PhosphorusTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#BaseSaturation
#+     - http://w3id.org/glosis/model/layerhorizon#Gypsum
#+     - http://w3id.org/glosis/model/layerhorizon#PotassiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#TotalCarbonateEquivalent
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityFineEarth
#+     - http://w3id.org/glosis/model/layerhorizon#ManganeseTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#BulkDensityWholeSoil
#+     - http://w3id.org/glosis/model/layerhorizon#AluminiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+     - http://w3id.org/glosis/model/layerhorizon#IronExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CoarseFragments
#+     - http://w3id.org/glosis/model/layerhorizon#SodiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#CationExchangeCapacitycSoil
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#AvailableWaterHoldingCapacity
#+     - http://w3id.org/glosis/model/layerhorizon#MagnesiumExchangeableBases
#+     - http://w3id.org/glosis/model/layerhorizon#SulfurTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumExtractableElements
#+     - http://w3id.org/glosis/model/layerhorizon#CopperTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#CalciumTotalElements
#+     - http://w3id.org/glosis/model/layerhorizon#Porosity
#+     - http://w3id.org/glosis/model/layerhorizon#BoronTotalElements
#+ defaults:
#+   - physioChemicalProperty: http://w3id.org/glosis/model/layerhorizon#NitrogenTotal
#+ transform: {
#+   "physioChemicalProperty": "?property",
#+   "$anchor": "physioChemicalProperty",
#+   "value": {
#+     "obs": "?obs",
#+     "value": "?value",
#+   },
#+ }


PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt/>
PREFIX glosis_lh: <http://w3id.org/glosis/model/layerhorizon#>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX geof: <http://www.opengis.net/def/function/geosparql/>
PREFIX iso: <http://w3id.org/glosis/model/iso28258/2013#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?obs ?value (REPLACE(STR(?_physioChemicalProperty_iri), "^.*#([^#]*)$", "$1") as ?property)
WHERE 
{
  {
    SELECT distinct ?obs ?value
    WHERE 
    {
       ?obs a ?_physioChemicalProperty_iri ;
         sosa:hasResult ?res ;
         sosa:hasFeatureOfInterest ?lay .
       ?res qudt:numericValue ?value .
       OPTIONAL { ?s ?p ?_minValue_integer }
       FILTER (?value > ?_minValue_integer) .
    }
  }
  UNION
  {
    SELECT ?obs ?value 
    WHERE
    {
       SERVICE <https://virtuoso.isric.org/sparql/> { 
         ?obs a ?_physioChemicalProperty_iri ;
            sosa:hasResult ?res ;
            sosa:hasFeatureOfInterest ?lay .
         ?res qudt:numericValue ?value .
         FILTER (?value > ?_minValue_integer) .
       }
    }
  } 
} ORDER BY DESC (?obs)