#+ method: POST
#+ endpoint: "https://www.foodie-cloud.org/sparql"

SELECT DISTINCT ?property
WHERE {
     VALUES (?property ) {
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph0-nh4cl")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-m3")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph8-unkn")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph0-cohex")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac-aas")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-edta")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac-fp")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph8-bacl2tea")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph-unkn-m3-spec")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-unkn")
     ("http://w3id.org/glosis/model/procedure#exchangeableBasesProcedure-ExchBases_ph7-nh4oac")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_cacl2")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap15")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-kurtz-bray")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nh4-co3-2-ambic1")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m3-spec")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m1")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-h2so4-nelson")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_dtpa")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap14")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-bray1")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_edta")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m2")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_naoac-morgan")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_capo4")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hotwater")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nahco3-olsen-dabin")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nh4ch3ch-oh-cooh-leuven")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_c6h8o7-reeuwijk")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hcl-nh4f-bray2")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_m3")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap21")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_hno3")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_nahco3-olsen")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_ap20")
     ("http://w3id.org/glosis/model/procedure#extractableElementsProcedure-Extr_h2so4-truog")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-kcl1m")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph7-caoac")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph8-unkn")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-unkn")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph8-bacl2tea")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph7-unkn")
     ("http://w3id.org/glosis/model/procedure#acidityExchangeableProcedure-ExchAcid_ph0-nh4cl")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-2.5")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-10")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-5")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-1")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-ECe_sat")
     ("http://w3id.org/glosis/model/procedure#electricalConductivityProcedure-EC_ratio1-2")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy04")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy01")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy05")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy06")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy02")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy07")
     ("http://w3id.org/glosis/model/procedure#gypsumProcedure-CaSO4_gy03")
     ("http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc100wp")
     ("http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc200wp")
     ("http://w3id.org/glosis/model/procedure#availableWaterHoldingCapacityProcedure-PAWHC_calcul-fc300wp")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn08")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn04")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-spec")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_kjeldahl")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-ht-leco")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_calcul-oc10")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_bremner")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_calcul")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_h2so4")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_tn06")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_nelson")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_kjeldahl-nh4")
     ("http://w3id.org/glosis/model/procedure#nitrogenTotalProcedure-TotalN_dc-ht-dumas")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-10")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-2.5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_sat")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-2")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-2")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-10")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_sat")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-1")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_sat")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-2.5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-2")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_ratio1-5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-2.5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-1")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_sat")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O_unkn-spec")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-10")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-1")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHCaCl2_ratio1-10")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-1")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHNaF_ratio1-2.5")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHKCl_ratio1-2")
     ("http://w3id.org/glosis/model/procedure#pHProcedure-pHH2O")
     }
}
